services:

  staffcheck-app:
    build: ./staffcheck-backend
    container_name: staffcheck-app
    ports:
      - '8085:8085'

    expose:
      - '8085'
    depends_on:
      - mysql


  staffcheck-angular:
    build: ./staffcheck-frontend
    container_name: staffcheck-angular
    ports:
      - '80:80'
    expose:
      - '80'




  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: EmployeeManagement
      MYSQL_ROOT_PASSWORD: 1234

    ports:
      - '3307:3306'

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql



volumes:
  mysql_data: